### ISSUE TITLE
Allow HTML fragments

### ISSUE THREAD

**Issue by davidosomething** [juvenn/mustache.vim#12]
for instance:

```
<tr data-id="{{id}}" class="cart-item">
  <th>{{name}}</th>
  <td>{{quantity}}</td>
</tr>
```

will throw a syntax error because the template doesn't have a `<table>` tag around it, but I'm just generating TRs for an existing table.

**Comment by bruno-** [comment]
Hi @davidosomething,
I think you reported a problem to the wrong open source project. I'm guessing there are problems with a framework you are using..
This project is a vim plugin and only provides syntax highlighting for mustache files.

Just to make sure - I did check the code chunk you provided and there is nothing unusual with it. The syntax highlighting for it is ok within a mustache file.

Please let me know if I'm missing the point - in the meanwhile I'm closing the issue.

**Comment by davidosomething** [comment]
Oh crap yea my bad.
