### ISSUE TITLE
ftdetect not working?

### ISSUE THREAD

**Issue by greg0ire** [juvenn/mustache.vim#2]
I installed your plugin _via_ pathogen, and I can't have syntax highlighting in a .handlebars file unless I explicitely set the filetype (like this `:setfiletype mustache`). I saw a condition in the file : `if has("autocmd")`, so I typed `:autocmd` and saw it was installed, obviously, so the condition should pass.

**Comment by nono** [comment]
For your information, I've made a fork of mustache.vim specifically for Handlebars: https://github.com/nono/vim-handlebars

**Comment by greg0ire** [comment]
I just installed it _via_ pathogen too and it works great... but I must type `:setfiletype handlebars`... I guess something must be missing in my vim configuration, but what?

**Comment by juvenn** [comment]
It does support .handlebars. Could you confirm this in `ftdetect/mustache.vim`?

```
if has("autocmd")
  au  BufNewFile,BufRead *.mustache,*.handlebars,*.hbs set filetype=mustache
endif
```

If a .mustache works, then .handlebars should work as well.

**Comment by greg0ire** [comment]
The fact is, it doesn't work for .mustache either, the detected filetype is html... I was mislead because html gives some coloration, but after setting the filetype to mustache, it is far better. My vim configuration is available [here](https://github.com/greg0ire/dotvim) if you want to take a look at it.

**Comment by juvenn** [comment]
Hi greg, sorry for late reply.

Your configuration is right as I can see. It should detect `*.mustache, *.handlebars, *.hbs`, as you can see in ftdetect/mustache.vim:

```
au  BufNewFile,BufRead *.mustache,*.handlebars,*.hbs set filetype=mustache
```

Can you try a new file with *.hbs extension?

**Comment by greg0ire** [comment]
Hello juvenn, thanks for the reply, I tried with a hbs copy of the handlebars file, and I got the same problem. I posted my problem [here](http://unix.stackexchange.com/questions/21843/filetype-not-detected) and got a solution using a filetype.vim file... strange.

**Comment by greg0ire** [comment]
My use of pathogen was in cause. Sorry for the inconvenience. I posted the solution [here](http://unix.stackexchange.com/questions/21843/filetype-not-detected

**Comment by juvenn** [comment]
That's great you've got it working, thanks :)
